services:
  mcp-server-postgres:
    container_name: mcp-server-postgres
    build: .
    env_file:
      - .env
    ports:
      - "8056:8056"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        compress: "true"